### ISSUE TITLE
Dismiss cookie disclaimer in LoginViewController

### ISSUE THREAD

**Issue by mycroftcanner** [TheM4hd1/SwiftyInsta#121]
It would be nice if the cookie disclaimer at the top of the screen could be dismissed automatically. Is that possible?

**Comment by sbertix** [comment]
It is, in theory. That's how it used to work.
Unfortunately, for some reasons I don't fully understand (I don't really know how Instagram could test for the web page integrity), messing with the login page code is always met with a blank page afterwords.
That's why the feature was never implemented in production.
