### ISSUE TITLE
Insta limits

### ISSUE THREAD

**Issue by hell4opt** [TheM4hd1/SwiftyInsta#125]
Do you know what limits Instagram has? in particular, to get a list of followers, after 3-4 receiving this method is banned for a day, and there still sometimes insta mixes left people with extradition, is it just me?)

**Comment by sbertix** [comment]
I personally do not, unfortunately.  

I've encountered the "followers/following problem" you've mentioned myself, but I believe it's more about Instagram having (maybe) discontinued/changed the expected-requests to those endpoints and moved on to new ones we don't know about, since it's tied to those specific ones, than the sheer amount of requests (the time delay between requests in `SwiftyInsta` deals exactly with that, and as long as it's not set to `0` you should be ok).  

I'm leaving this open for a while, in case anyone has more info on this topic.

**Comment by hell4opt** [comment]
> I personally do not, unfortunately.
> 
> I've encountered the "followers/following problem" you've mentioned myself, but I believe it's more about Instagram having (maybe) discontinued/changed the expected-requests to those endpoints and moved on to new ones we don't know about, since it appears to be tied to those specific ones, than the sheer amount of requests (the time delay in `SwiftyInsta` deals exactly with that, and as long as it's not set to `0` and you don't spam requests, you should be ok).
> 
> I'm leaving this open for a while, in case anyone has more info on this topic.

thanks for the answer, it's a shame) maybe a lot of applications work somehow, we see they have new endpoints

can you write an example of a correct request for a list of fallowers?

**Comment by sbertix** [comment]
> can you write an example of a correct request for a list of fallowers?

Sure thing 😊 

```swift
/* given ur `APIHandler` strongly referenced instance `handler` */
        handler.users.following(user: .me,
                                with: .everything,
                                updateHandler: nil, /* optional */
                                completionHandler: { _, _ in /* do sth */ })
```
