### ISSUE TITLE
Total Post,Follower,Following Count

### ISSUE THREAD

**Issue by arda0011** [TheM4hd1/SwiftyInsta#147]
What is the easiest way to get total post, follower and following count in Api?

I tried with below method but it did not return this counts
handler.users.user(.me)

**Comment by sbertix** [comment]
Posts, followers and following count are not exposed to `User` by design, since those properties are not actually populated every time a `User`-like object is returned by a request.  
You can always access them through the `User` you get by calling the method you mentioned and then referencing directly the `rawResponse`.  

```swift
handler.users.user(.me) {
    guard let user = try? $0.get() else { return }
    let posts = user.rawResponse.mediaCount.int ?? 0
    let followers = user.rawResponse.followerCount.int ?? 0
    let following = user.rawResponse.followingCount.int ?? 0
}
```
