### ISSUE TITLE
WebViewAuthenticator Implementation

### ISSUE THREAD

**Issue by MariaJsn** [TheM4hd1/SwiftyInsta#170]
Hi,

For the webview problem I think there is not any solution. 
Can we implement WebViewAuthenticator like @sbertix repository to solve this problem? Is it possible?
Or there is nothing to do?

What do you think @TheM4hd1 @sbertix 

Thanks,
Maria

**Comment by sbertix** [comment]
`WebViewAuthenticator` does nothing different than `LoginWebView`.  
I'm saying this for the last time: **there's nothing wrong with `LoginWebView`** hahaha
The problem is in Instagram security system with matching IPs, `spammer` accounts and user agents, meaning `WebViewAuthenticator` in **Swiftagram** will probably stop working too, eventually.
