### ISSUE TITLE
I cannot login when I change user-agent.

### ISSUE THREAD

**Issue by Yagia** [TheM4hd1/SwiftyInsta#178]
When I change user-agent to with below or  with anything
For example:
login.userAgent = "(iPhone Build/LRX21T) AppleWebKit/537.36 Mobile Safari/537.36"

I cannot login. Is there a sample user-agent so that it doesn't write google play at the top banner?

▿ Result<(Response, APIHandler), Error>
  ▿ failure : GenericError
    - custom : "https://i.instagram.com/api/v1/accounts/current_user/.\nInvalid response.\nProcessing handler returned `nil`.\n403"

**Comment by sbertix** [comment]
Please check the closed issues before opening a new one.  
It's a topic already discussed in depth in several ones (e.g. #163).  
We have no solution. I've pushed a PR removing the custom user agent feature. I haven't heard from @TheM4hd1, so since it's been quite a while I'll probably merge it myself soon.
