### ISSUE TITLE
How to handle pagination

### ISSUE THREAD

**Issue by mzgnr** [TheM4hd1/SwiftyInsta#24]
Any example with pagination ?

**Comment by mzgnr** [comment]
Another small thing, After logged in, for a second if time instagram home page is being visible, I thought that didstartprovisionalnavigation or didReceiveServerRedirectForProvisionalNavigation should be used to pop to previous controller before redirecting, but i cloud not make it work actually. Any ideas about it ?

**Comment by TheM4hd1** [comment]
Every time we scroll down in our devices to load more data (followers, photos, conversations...), that's called pagination.

When you get Instagram's response, it may contain a next_max_id key, which means there is more data you can load. In order to paginate, you will have to pass that param to the function. 
Here is an example:

```swift
try? handler.getUserMedia(for: username, paginationParameter: PaginationParameters.maxPagesToLoad(maxPages: 10), completion: { (result) in
    if result.isSucceeded {
        let medias = result.value!
        medias.forEach({ (media) in
            media.items!.forEach({ (item) in
                // get media url or something else here.
            })
        })
    }
})
```

Unfortunately I’ve made a mistake when developing **pagination** functions. When you set a ```maxPages``` value to pagination, _it will receives all data first_, **then** it will returns data to you. And it's not efficient.
I will release a fix for pagination functions to make them more efficent.
If you don’t know how many pages may exists, you can use ```Int.max``` value, the function will stops automatically when pages finished.


### For your second question,
it's possible to add 2 more functions to ```InstagramLoginWebViewDelegate``` protocol.
For Example: 
```swift
public protocol InstagramLoginWebViewDelegate {
    func userLoggedSuccessfully()
    func webViewFinishedToLoadUser(sessionCache : SessionCache, handler: APIHandlerProtocol)
    func willStartLoading()
    func didFinishedLoading()
}
``` 

```swift
public override func webView(_ webView: WKWebView, didStartProvisionalNavigation navigation: WKNavigation!) {
    loginDelegate?.willStartLoading()
}

public override func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
    loginDelegate?.didFinishedLoading()
    
    self.fetchCookies(completion: { (cookies) in
        let instagramCookies =  cookies?.getInstagramCookies()
        self.isUserLoggedIn(instagramCookies: instagramCookies!)
    })
}
```

**Comment by canaksoy** [comment]
> Unfortunately I’ve made a mistake when developing pagination functions. When you set a maxPages value to pagination, it will receives all data first, then it will returns data to you. And it's not efficient.
I will release a fix for pagination functions to make them more efficent.

when will you fix pagination? How can we help? @TheM4hd1

**Comment by TheM4hd1** [comment]
@canaksoy I'll fix it this week.
