### ISSUE TITLE
Merging `Siwa` into `SwiftyInsta`

### ISSUE THREAD

**Issue by sbertix** [TheM4hd1/SwiftyInsta#57]
**[DONE IN `SwiftyInsta` v. `2.0`]**

The login mechanics used in [Siwa](https://github.com/TheM4hd1/Siwa) are far superior to the ones in `SwiftyInsta`, yet `SwiftyInsta` still provides a way for headless login, only resulting in code duplication.

Instead of dropping support for authentication through _username_ and _password_ from `SwiftyInsta` (like I proposed in my draft for `2.0` now in the `development` branch), why not adding all of `Siwa` functionalities back to `SwiftyInsta`?

What's the reasoning behind having them as separate frameworks?

**Comment by TheM4hd1** [comment]
I developed `Siwa` for a company to fix their login issues (sentry_block), and because `Siwa` using the  `Web API` I decided to create a new framework for Instagram Web API, but I didn't had time to implement all feature so I just decided to leave it as an alternative Login way.
and One of the reasons I didn't combine it with `SwiftyInsta` was that many users were fine with the Private API Login, Since we removed the `user & pass` login from `SwiftyInsta` this is a good timing to merge it with `SwiftyInsta`

**Comment by sbertix** [comment]
Do you mind if I try to add it back to `SwiftyInsta` and send a _pr_ to `development` once I'm done, then? 😊

**Comment by TheM4hd1** [comment]
sure, why not.
Good idea.
