### ISSUE TITLE
Login With Cookies

### ISSUE THREAD

**Issue by TolgaKaramese** [TheM4hd1/SwiftyInsta#97]
Which method should i use to login user with cookies. I am try to log in with hard coded cookies, user is not persisted before, so i need to log in with cookies for example obtained from api. 
Lastly, the swiftyinstatest folder was very helpful for me, it would be perfect if you guys add it on new version.

**Comment by sbertix** [comment]
In `2.0` this is no longer exposed **by design**, as it would allow for a far too easy mishandling of cookies when using the library.

However, since `Authentication.Response` conforms to `Encodable` and not only `Decodable`, nothing's stopping anyone from populating a dictionary with all its stored properties (including the `HTTPCookies`do `data`), encoding it to JSON, decoding it to `Authentication.Response` and handling it to the authentication method.
Or if you're okay with editing some code locally, you could just create a custom `init` in `Authentication.Response` matching your own need.

`Tests` are definitely coming back in the future. 
Writing `2.0` was not an easy or short timed task. Having a better documented, way easier to use library has been the main focus. And I feel like we truly achieved that.
Being every method self contained right now, it's more likely `Tests` are reverting back to be just _build tests_, tracking when methods break and such.
We'll discuss adding an actual `Example` though 💪
